export default {
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_SUGGESTED_PRODUCTS: 'GET_SUGGESTED_PRODUCTS',
  CLEAR_ERRORS: 'CLEAR_ERRORS'
};
